title: ""
description: ""
header_pages:
  - index.html
  - en/privacy.md
  - en/term_of_services.md

# Language settings
default_lang: en
languages:
  en:
    label: English
    privacy_policy: /en/privacy.html
    terms_of_service: /en/term_of_services.html
  vi:
    label: Tiếng Việt
    privacy_policy: /vi/privacy.html
    terms_of_service: /vi/term_of_services.html